name: flutter_leak_radar_workspace
publish_to: none
environment:
  sdk: ">=3.10.0 <4.0.0"
workspace:
  - packages/flutter_leak_radar
  - packages/flutter_leak_radar_lint
  - packages/flutter_leak_radar_lint/example
dev_dependencies:
  melos: ^6.0.0
