name: flutter_leak_radar_lint_example
publish_to: none
environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.8.1
  flutter_leak_radar_lint:
    path: ..
